import { spawn } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { constants } from 'node:fs';
import { access, chmod, lstat, mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { classifyPackageFailure, writeDiagnosticLog } from './diagnostics.mjs';

const LOCKS = { npm: ['npm-shrinkwrap.json', 'package-lock.json'], pnpm: ['pnpm-lock.yaml'], yarn: ['yarn.lock'], bun: ['bun.lock', 'bun.lockb'] };
const INPUTS = ['package.json', ...Object.values(LOCKS).flat(), '.npmrc', '.yarnrc', '.yarnrc.yml', 'pnpm-workspace.yaml', 'bunfig.toml'];
const LAUNCHER_MARKER = '# Generated by Repo Dashboard.\n';

export class ProjectInstallError extends Error {
  constructor(message, statusCode = 409) {
    super(message);
    this.name = 'ProjectInstallError';
    this.statusCode = statusCode;
  }
}

function identity({ directory, fullName } = {}) {
  if (typeof directory !== 'string' || !path.isAbsolute(directory)
    || typeof fullName !== 'string' || !/^[a-z\d](?:[a-z\d-]{0,37}[a-z\d])?\/[a-z\d_.-]{1,100}$/i.test(fullName)
    || ['.', '..', '.git'].includes(fullName.split('/')[1].toLowerCase())) {
    throw new ProjectInstallError('Choose a repository with an absolute local folder and GitHub owner/name.', 400);
  }
  return { directory: path.resolve(directory), fullName };
}

async function contents(file) {
  try {
    const info = await lstat(file);
    if (!info.isFile() || info.isSymbolicLink()) throw new ProjectInstallError('Project setup files must be regular files inside this checkout.');
    if (info.size > 32 * 1024 * 1024) throw new ProjectInstallError('A project setup file is too large to inspect. Set up this project in Terminal.');
    return await readFile(file);
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

async function exists(file) { return Boolean(await lstat(file).catch(() => null)); }
function shellQuote(value) { return `'${value.replaceAll("'", "'\\''")}'`; }

async function isStaticManifest(directory, manifest) {
  // Some browser apps use package.json only for tests. Do not require npm to
  // install those tools to launch already runnable HTML (for example impact-sim).
  // Keep build/framework projects out of this fallback: a source index.html is
  // not proof that a bundled or transpiled app can run in a static server.
  if (manifest.workspaces || ['dependencies', 'optionalDependencies', 'peerDependencies']
    .some((field) => Object.keys(manifest[field] || {}).length)) return false;
  if (Object.keys(manifest.scripts || {}).some((name) => !/^(?:pre|post)?(?:test|check|lint|format)(?::[a-z\d:_-]+)?$/i.test(name))) return false;
  const html = await contents(path.join(directory, 'index.html'));
  if (!html) return false;
  for (const match of html.toString('utf8').matchAll(/\b(?:src|href)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/gi)) {
    const target = (match[1] ?? match[2] ?? match[3]).split(/[?#]/, 1)[0];
    if (/\.(?:[cm]?tsx?|jsx|vue|svelte|scss|sass|less)$/i.test(target) || /(?:^|\/)node_modules\//i.test(target)) return false;
  }
  return true;
}

function isElectronPackagingBuild(manifest) {
  const usesElectron = ['dependencies', 'devDependencies', 'optionalDependencies']
    .some((field) => typeof manifest[field]?.electron === 'string');
  // npm run build also runs these hooks. They may compile the app or create
  // required assets even when the build command itself only packages Electron.
  if (['prebuild', 'postbuild'].some((name) => typeof manifest.scripts?.[name] === 'string'
    && manifest.scripts[name].trim())) return false;
  // Packaging an Electron app is optional when its start script runs source.
  // Match only a standalone packaging command; retain compile/build pipelines.
  return usesElectron && /^(?:electron-builder|electron-packager)(?:[ \t]+[a-z\d_./:=@-]+)*[ \t]*$/i.test(manifest.scripts.build.trim());
}

/** Read-only project detection. No repository-supplied commands run here. */
export async function inspectProject(input) {
  const { directory } = identity(input);
  const files = new Map(await Promise.all(INPUTS.map(async (name) => [name, await contents(path.join(directory, name))])));
  const hash = createHash('sha256');
  for (const [name, data] of files) hash.update(name).update('\0').update(data || '<absent>').update('\0');
  const fingerprint = hash.digest('hex');
  const unsupported = (message) => ({ kind: 'unsupported', supported: false, ready: false, fingerprint, message });
  if (!files.get('package.json')) {
    if (await contents(path.join(directory, 'index.html'))) return { kind: 'static', supported: true, ready: false, fingerprint, message: 'A local browser launcher can be installed for this HTML app.' };
    return unsupported('Source is downloaded. Automatic setup supports a root package.json with a dev/start script, or a root index.html. Follow this repository’s README for its setup.');
  }
  let manifest;
  try { manifest = JSON.parse(files.get('package.json')); } catch { return unsupported('package.json is not valid JSON. Fix it before installing this app.'); }
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) return unsupported('package.json must contain a project object.');
  const modules = await lstat(path.join(directory, 'node_modules')).catch((error) => { if (error.code === 'ENOENT') return null; throw error; });
  if (modules && (!modules.isDirectory() || modules.isSymbolicLink())) return unsupported('node_modules is a symlink or is not a directory. Move it aside in Terminal before installing this app.');
  const script = ['dev', 'start'].find((name) => typeof manifest.scripts?.[name] === 'string' && manifest.scripts[name].trim());
  if (!script) {
    if (await isStaticManifest(directory, manifest)) return { kind: 'static', supported: true, ready: false, fingerprint,
      message: 'Install a local browser launcher for this HTML app. Its package.json contains development checks only; no dependencies are needed to run it.' };
    return unsupported('Source is downloaded, but package.json has no dev or start script and does not describe a build-free HTML app. Follow the README to run this project.');
  }
  const detected = Object.keys(LOCKS).filter((manager) => LOCKS[manager].some((name) => files.get(name)));
  let manager;
  if (manifest.packageManager !== undefined) {
    const declared = /^(npm|pnpm|yarn|bun)@(\d[^\s/]*)$/.exec(manifest.packageManager);
    if (!declared) return unsupported('The packageManager field does not name a supported npm, pnpm, yarn, or bun version. Follow the README for setup.');
    manager = declared[1];
  } else if (detected.length > 1) return unsupported('Several package managers have lockfiles. Set packageManager in package.json to choose the correct installer.');
  else manager = detected[0] || 'npm';
  if (detected.length && !detected.includes(manager)) return unsupported(`package.json selects ${manager}, but the lockfile belongs to another package manager. Resolve this in Terminal before setup.`);
  const hasDependencies = ['dependencies', 'devDependencies', 'optionalDependencies', 'peerDependencies'].some((field) => Object.keys(manifest[field] || {}).length > 0) || Boolean(manifest.workspaces);
  return { kind: 'node', supported: true, ready: false, manager, script, fingerprint, hasDependencies,
    needsBuild: script === 'start' && typeof manifest.scripts?.build === 'string' && Boolean(manifest.scripts.build.trim()) && !isElectronPackagingBuild(manifest),
    hasLock: LOCKS[manager].some((name) => files.get(name)),
    message: `Install dependencies with ${manager} and create a launcher for ${manager} run ${script}.` };
}

/** Bounded subprocess with process-group cancellation; logs never go to HTTP errors. */
function runBounded(file, args, { cwd, env, timeoutMs, maxBytes = 2 * 1024 * 1024 }) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    let timer;
    let settled = false;
    let failure;
    const child = spawn(file, args, { cwd, env, shell: false, detached: process.platform !== 'win32', stdio: ['ignore', 'pipe', 'pipe'] });
    const kill = () => {
      try { if (process.platform !== 'win32' && child.pid) process.kill(-child.pid, 'SIGKILL'); else child.kill('SIGKILL'); }
      catch { try { child.kill('SIGKILL'); } catch { /* Process already exited. */ } }
    };
    const finish = (error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      const output = Buffer.concat(chunks).toString('utf8');
      if (error) { kill(); error.output = output; reject(error); }
      else resolve({ output });
    };
    const abort = (error) => {
      failure ||= error;
      kill();
      // Destroy inherited pipes so a detached grandchild cannot hold them open.
      // Still wait for the direct child's close event before releasing the lock.
      child.stdout.destroy();
      child.stderr.destroy();
    };
    const collect = (chunk) => {
      if (settled || failure) return;
      const remaining = maxBytes - size;
      chunks.push(chunk.subarray(0, remaining));
      size += Math.min(chunk.length, remaining);
      if (chunk.length > remaining) abort(Object.assign(new Error('Install output limit exceeded.'), { code: 'OUTPUT_LIMIT' }));
    };
    child.stdout.on('data', collect);
    child.stderr.on('data', collect);
    child.once('error', (error) => finish(failure || error));
    child.once('close', (code) => finish(failure || (code === 0 ? null : Object.assign(new Error('Project command failed.'), { code }))));
    timer = setTimeout(() => abort(Object.assign(new Error('Install timed out.'), { code: 'ETIMEDOUT' })), timeoutMs);
    timer.unref();
  });
}

async function atomicWrite(file, text, mode) {
  const temporary = `${file}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporary, text, { mode, flag: 'wx' });
    await rename(temporary, file);
    await chmod(file, mode);
  } finally { await rm(temporary, { force: true }).catch(() => {}); }
}

export function createProjectInstaller({
  stateRoot = path.join(homedir(), 'Library', 'Application Support', 'Repo Dashboard Projects'),
  launchersRoot = path.join(homedir(), 'Applications', 'Repo Apps'),
  runtimeRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'),
  timeoutMs = 10 * 60_000,
  env = process.env,
  platform = process.platform,
} = {}) {
  stateRoot = path.resolve(stateRoot);
  launchersRoot = path.resolve(launchersRoot);
  runtimeRoot = path.resolve(runtimeRoot);
  const childEnv = { ...env, NODE_ENV: 'development', CI: '1', COREPACK_ENABLE_AUTO_PIN: '0', COREPACK_ENABLE_DOWNLOAD_PROMPT: '0' };
  // A browser's GitHub token is never included in these options. Preserve the
  // user's package registry authentication/environment for their own projects.
  const pending = new Set();

  async function outputDirectory(base, directory) {
    for (const folder of [base, directory]) {
      await mkdir(folder, { recursive: true, mode: 0o700 });
      const info = await lstat(folder);
      if (!info.isDirectory() || info.isSymbolicLink()) throw new ProjectInstallError('The app state or launcher folder is a symlink or is not a regular directory. Choose a regular folder before setup.');
    }
  }

  function paths(fullName) {
    const [owner, repo] = fullName.split('/');
    return { recordPath: path.join(stateRoot, owner, `${repo}.json`), logPath: path.join(stateRoot, owner, `${repo}.install.log`), launcherPath: path.join(launchersRoot, owner, `${repo}.command`) };
  }

  async function findManager(manager) {
    for (const folder of (childEnv.PATH || '').split(path.delimiter).filter((part) => path.isAbsolute(part))) {
      const candidate = path.join(folder, manager);
      try { await access(candidate, constants.X_OK); return candidate; } catch { /* Try the next PATH entry. */ }
    }
    throw new ProjectInstallError(`${manager} is required by this repository but is not installed or not on PATH. Install ${manager}, reopen Repo Dashboard, and choose Install locally again.`, 503);
  }

  function descriptor(project, launcherPath, ready = false) {
    const { fingerprint, hasDependencies, hasLock, needsBuild, ...publicFields } = project;
    return { ...publicFields, ready, ...(project.supported ? { launcherPath } : {}) };
  }

  async function describe(input) {
    const { directory, fullName } = identity(input);
    let project;
    try { project = await inspectProject({ directory, fullName }); }
    catch (error) { return { kind: 'unsupported', supported: false, ready: false, message: error instanceof ProjectInstallError ? error.message : 'Project setup files could not be read. Check folder permissions in Terminal.' }; }
    const { recordPath, launcherPath } = paths(fullName);
    if (!project.supported) return descriptor(project, launcherPath);
    let saved;
    try { saved = JSON.parse(await readFile(recordPath, 'utf8')); } catch { /* Not installed yet. */ }
    let ready = saved?.version === 1 && saved.directory === directory && saved.fullName === fullName && saved.fingerprint === project.fingerprint
      && saved.kind === project.kind && saved.script === project.script && saved.manager === project.manager;
    if (ready) ready = (await readFile(launcherPath, 'utf8').catch(() => '')).includes(LAUNCHER_MARKER);
    if (ready && project.kind === 'node' && project.hasDependencies) {
      ready = await exists(path.join(directory, 'node_modules')) || (project.manager === 'yarn' && await exists(path.join(directory, '.pnp.cjs')));
    }
    return { ...descriptor(project, launcherPath, Boolean(ready)), message: ready ? 'App installed locally. Double-click its launcher or choose Launch app.'
      : saved ? 'Project setup changed or installed files are missing. Choose Install locally to refresh dependencies and the launcher.' : project.message };
  }

  async function install(input) {
    const { directory, fullName } = identity(input);
    const key = fullName.toLowerCase();
    if (pending.has(key)) throw new ProjectInstallError('This app is already being installed. Wait for setup to finish.');
    pending.add(key);
    try {
      const project = await inspectProject({ directory, fullName });
      const { recordPath, logPath, launcherPath } = paths(fullName);
      if (!project.supported) return descriptor(project, launcherPath);
      const existingLauncher = await readFile(launcherPath, 'utf8').catch((error) => { if (error.code === 'ENOENT') return null; throw error; });
      if (existingLauncher !== null && !existingLauncher.includes(LAUNCHER_MARKER)) throw new ProjectInstallError('A different file already uses this launcher name. Move it aside before installing this app.');
      await outputDirectory(stateRoot, path.dirname(recordPath));
      await outputDirectory(launchersRoot, path.dirname(launcherPath));
      // Invalidate a previous success before running a possibly failing repair.
      await rm(recordPath, { force: true });
      let managerPath;
      if (project.kind === 'node') {
        managerPath = await findManager(project.manager);
        let args;
        if (project.manager === 'npm') args = [project.hasLock ? 'ci' : 'install', ...(project.hasLock ? [] : ['--package-lock=false']), '--global=false', '--include=dev', '--ignore-scripts=false', '--no-audit', '--no-fund'];
        if (project.manager === 'pnpm') args = ['install', project.hasLock ? '--frozen-lockfile' : '--no-lockfile', '--prod=false'];
        if (project.manager === 'bun') args = ['install', project.hasLock ? '--frozen-lockfile' : '--no-save'];
        if (project.manager === 'yarn') {
          let version;
          try { version = await runBounded(managerPath, ['--version'], { cwd: directory, env: childEnv, timeoutMs: 30_000, maxBytes: 64 * 1024 }); }
          catch { throw new ProjectInstallError('Yarn could not start. Check the project’s required Yarn version in Terminal and retry.', 503); }
          const major = Number(version.output.trim().split('.')[0]);
          if (!Number.isInteger(major) || major < 1) throw new ProjectInstallError('Yarn did not report a supported version. Check Yarn in Terminal.');
          if (major >= 2 && !project.hasLock) throw new ProjectInstallError('Modern Yarn requires a committed yarn.lock for automatic setup. Run yarn install in Terminal, commit the lockfile, then try again.');
          args = major >= 2 ? ['install', '--immutable'] : ['install', project.hasLock ? '--frozen-lockfile' : '--no-lockfile', '--non-interactive', '--production=false'];
        }
        let setupStage = 'install';
        let log = `${project.manager} ${args.join(' ')}\nRepository: ${fullName}\nNode: ${process.version}\nPlatform: ${process.platform} ${process.arch}\n`;
        try {
          const result = await runBounded(managerPath, args, { cwd: directory, env: childEnv, timeoutMs });
          log += result.output;
          await writeDiagnosticLog({ root: stateRoot, fullName, kind: 'install', content: log });
          if (project.needsBuild) {
            setupStage = 'build';
            log += `\n${project.manager} run build\n`;
            const built = await runBounded(managerPath, ['run', 'build'], { cwd: directory, env: childEnv, timeoutMs });
            log += built.output;
            await writeDiagnosticLog({ root: stateRoot, fullName, kind: 'install', content: log });
          }
        } catch (error) {
          const detail = classifyPackageFailure(error, { stage: setupStage });
          log += `\nStage: ${setupStage}\nReason: ${detail.reason}\n${error.output || 'The command or diagnostic log write could not finish.\n'}`;
          const written = await writeDiagnosticLog({ root: stateRoot, fullName, kind: 'install', content: log }).then(() => true, () => false);
          const label = setupStage === 'build' ? 'Project build failed' : 'Dependency installation failed';
          throw new ProjectInstallError(`${label} (${detail.reason}). ${detail.message} Your source remains local. ${written ? `Check ${logPath}` : 'The diagnostic log could not be written; check folder permissions and disk space'}, then choose Install locally again.`, detail.statusCode);
        }
        const after = await inspectProject({ directory, fullName });
        if (!after.supported || after.kind !== project.kind || after.fingerprint !== project.fingerprint) throw new ProjectInstallError('An installation script changed project setup files or created an invalid dependency folder. Review the changes in Terminal, then choose Install locally again.');
        if (project.hasDependencies && !await exists(path.join(directory, 'node_modules')) && !(project.manager === 'yarn' && await exists(path.join(directory, '.pnp.cjs')))) {
          throw new ProjectInstallError('The package manager finished without creating dependency files. Review the project setup in Terminal.');
        }
      }
      const record = { version: 1, directory, fullName, kind: project.kind, manager: project.manager, managerPath, script: project.script,
        fingerprint: project.fingerprint, installedAt: new Date().toISOString() };
      const launcher = '#!/bin/bash\n' + LAUNCHER_MARKER
        + 'export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"\n'
        + `exec ${shellQuote(process.execPath)} ${shellQuote(path.join(runtimeRoot, 'scripts', 'project-launcher.mjs'))} ${shellQuote(recordPath)}\n`;
      await atomicWrite(launcherPath, launcher, 0o700);
      await atomicWrite(recordPath, `${JSON.stringify(record, null, 2)}\n`, 0o600);
      return { ...await describe({ directory, fullName }), message: `Installed ${fullName} locally. Double-click ${launcherPath} to run it.` };
    } finally { pending.delete(key); }
  }

  async function launch(input) {
    const project = await describe(input);
    if (!project.ready) throw new ProjectInstallError(project.message);
    if (childEnv.REPO_DASHBOARD_NO_OPEN !== '1') {
      if (platform !== 'darwin') throw new ProjectInstallError('Launch app is available when this dashboard runs on your Mac.', 400);
      try { await runBounded('/usr/bin/open', ['-a', 'Terminal', project.launcherPath], { env: childEnv, timeoutMs: 10_000 }); }
      catch { throw new ProjectInstallError('macOS could not open the app launcher. Double-click its .command file in Finder.', 502); }
    }
    return { ...project, message: `Opening ${identity(input).fullName}. App output appears in Terminal.` };
  }

  return { describe, install, launch };
}
